### ISSUE TITLE
Bug：我发现一旦启用图片渲染，就会导致gpt3插件导入失败

### ISSUE THREAD

**Issue by kerios22** [chrisyy2003/lingyin-bot#12]
在使用作者开发的插件进行配置的过程中，我一旦开启了图片渲染改为true，就会导致插件无法导入。起初我以为是自己没有配置对config，但是我更改默认的config的时候，发现也是存在这个问题的。报错如下：
12-20 21:07:01 [ERROR] nonebot | Failed to import "nonebot_plugin_gpt3"
Traceback (most recent call last):
  File "k:\项目\个人项目\AI\cq-http\Alice\bot.py", line 24, in <module>
    nonebot.load_plugin('nonebot_plugin_gpt3')
  File "C:\Python\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Python\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Python\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Python\lib\site-packages\nonebot_plugin_gpt3\__init__.py", line 108, in <module>
    from nonebot_plugin_htmlrender import md_to_pic
  File "C:\Python\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 4, in <module>
    from .browser import get_browser, get_new_page, shutdown_browser
  File "C:\Python\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 18, in <module>
    from playwright.async_api import Page, Error, Browser, Playwright, async_playwright
  File "C:\Python\lib\site-packages\playwright\async_api\__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "C:\Python\lib\site-packages\playwright\async_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Python\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Python\lib\site-packages\playwright\_impl\_connection.py", line 23, in <module>
    from greenlet import greenlet
  File "C:\Python\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module

**Comment by chrisyy2003** [comment]
```
from nonebot_plugin_htmlrender import md_to_pic
File "C:\Python\lib\site-packages\nonebot_plugin_htmlrender_init.py", line 4, in
from .browser import get_browser, get_new_page, shutdown_browser
File "C:\Python\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 18, in
from playwright.async_api import Page, Error, Browser, Playwright, async_playwright
File "C:\Python\lib\site-packages\playwright\async_api_init.py", line 25, in
import playwright.async_api._generated
File "C:\Python\lib\site-packages\playwright\async_api_generated.py", line 25, in
from playwright._impl._accessibility import Accessibility as AccessibilityImpl
File "C:\Python\lib\site-packages\playwright_impl_accessibility.py", line 17, in
from playwright._impl.connection import Channel
File "C:\Python\lib\site-packages\playwright_impl_connection.py", line 23, in
from greenlet import greenlet
File "C:\Python\lib\site-packages\greenlet_init.py", line 29, in
from ._greenlet import _C_API # pylint:disable=no-name-in-module
```

看样子是依赖的nonebot_plugin_htmlrender库的问题，你安装plawright了没

pip3 install playwright && playwright install 进行安装

**Comment by kerios22** [comment]
感谢你的回复。抱歉我对程序的不熟练。我用你的方法解决了这个问题
