### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ANGJustinl** [chrisyy2003/lingyin-bot#4]
`12-15 12:10:09 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_multi_chatgpt"`这里确定加载了，但是没有这个地方说的初始化成功
![image](https://user-images.githubusercontent.com/96008766/207770963-c200ee78-6d05-4443-a402-735f5598387e.png)

 _报错代码从触发handler到结束_
![image](https://user-images.githubusercontent.com/96008766/207771462-0ed821bb-19fb-40c5-9c47-263b0db3747e.png)
![image](https://user-images.githubusercontent.com/96008766/207771487-a3681fb0-01fe-494c-b5c8-49c52755b041.png)

然后这里报了list的问题，我的token是这样配置的
![image](https://user-images.githubusercontent.com/96008766/207771153-7a55d772-a7df-4ed2-b7cf-cfe146d4065f.png)

**Comment by ANGJustinl** [comment]
12-15 12:11:32 [SUCCESS] nonebot | OneBot V11 2720054688 | [message.group.normal]: Message -1499185332 from 77139032@[群
:696748432] "chat 114514"
12-15 12:11:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_multi_chatgpt)
12-15 12:11:33 [INFO] nonebot_plugin_multi_chatgpt | False False
12-15 12:11:33 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_multi_chatgpt) running complete
12-15 12:11:33 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_multi_chatgpt) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in _
_call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in m
ain
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in i
nvoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in i
nvoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in in
voke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line
30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", lin
e 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273,
 in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", li
ne 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in
run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in
 run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142,
in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 188,
in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matche
r.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matche
r.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.p
y", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_multi_chatgpt\__
init__.py", line 155, in _
    resp = await get_chat_response(session_id, msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_multi_chatgpt\__
init__.py", line 98, in get_chat_response
    chatbot = chat_bot_list[index]
IndexError: list index out of range

**Comment by chrisyy2003** [comment]
fix，请看最新的文档，https://github.com/chrisyy2003/lingyin-bot/tree/main/plugins/chatGPT

此外，现在不推荐使用逆向的api，稳定性太差

推荐使用openai官方库
